import * as kebab from '#kebab/index.js';
import * as lCore from '#kebab/lib/core.js';
import sMod from '#kebab/sys/mod.js';

/*
// --- MYSQL ---
CREATE TABLE `m_test`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` char(4) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `token` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `point` point NOT NULL,
  `polygon` polygon NULL,
  `json` json NULL,
  `time_add` bigint NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `time_add`(`time_add` ASC) USING BTREE,
  UNIQUE INDEX `utoken`(`token` ASC) USING BTREE,
  UNIQUE INDEX `uname`(`name` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
// --- PGSQL ---
CREATE TABLE "m"."test" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE  1 MAXVALUE 9223372036854775807 START 1 CACHE 1),
  "name" char(4) COLLATE "pg_catalog"."default" NOT NULL,
  "token" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "point" point NOT NULL,
  "polygon" polygon,
  "json" jsonb,
  "time_add" int8 NOT NULL,
  CONSTRAINT "test_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "m"."test" OWNER TO "postgres";
CREATE INDEX "time_add" ON "m"."test" USING btree (
  "time_add" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "uname" ON "m"."test" USING btree (
  "name" COLLATE "pg_catalog"."default" "pg_catalog"."bpchar_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "utoken" ON "m"."test" USING btree (
  "token" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
*/

export default class extends sMod {

    protected static _$table = 'test';

    protected static _$primary = 'id';

    protected static _$key = 'token';

    protected static _$index = 'utoken';

    /* eslint-disable @typescript-eslint/naming-convention */

    declare public id: number;

    declare public name: string;

    declare public token: string;

    declare public point: { 'x': number; 'y': number; };

    declare public polygon: Array<Array<{ 'x': number; 'y': number; }>>;

    declare public json: kebab.Json;

    declare public time_add: number;

    /* eslint-enable */

    protected _keyGenerator(): string {
        return 'test_' + lCore.rand(0, 3).toString();
    }

}
